% mex_compile_prepare_a_matrix.m
% Adjust include and library paths as needed
mexcuda -v ...
    -L"/usr/local/cuda/lib64" -lcudart -lcuda ...
    'NVCCFLAGS=-gencode=arch=compute_89,code=sm_89' ...
    -lccglib ...
    prepare_a_matrix_mex.cu ../src/prepare_a_matrix.cu

