% mex_compile_prepare_a_matrix.m
% Adjust include and library paths as needed
mexcuda ...
    -I'../include' ...            % for tcbf.h if needed
    -I'../src' ...                % for prepare_a_matrix.h
    -I'/path/to/ccglib/include' ...
    -I'/path/to/cxxopts/include' ...
    -L'/path/to/ccglib/lib' -lccglib ...
    -L'/path/to/cuda/lib64' -lcudart -lcuda ...
    prepare_a_matrix_mex.cu ../src/prepare_a_matrix.cu
